[[PThreadPool]]
arch = "aarch64"
git-tree-sha1 = "36030e81bcfdc4d1a2353be6efcacc1c68a0c69d"
os = "macos"

    [[PThreadPool.download]]
    sha256 = "2b7cae060c95f02614f9226c29b188f41c5d7d91d4c57764b9f853c88783cad3"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201005+0/PThreadPool.v0.0.20201005.aarch64-apple-darwin.tar.gz"
[[PThreadPool]]
arch = "aarch64"
git-tree-sha1 = "818528fa56f0cd3e25cebab52e0ab00f11541a37"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "a329393e4273c9ef4f6ac7a0e0f62b25feba0608b6bfd5d12c5fdf1ab3a0c9a4"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201005+0/PThreadPool.v0.0.20201005.aarch64-linux-gnu.tar.gz"
[[PThreadPool]]
arch = "aarch64"
git-tree-sha1 = "87eaf406d12b1fb4f6116dcb53b005bb02c7ec73"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "6c746ac0aaa66e3f06815fa6303bb9560f7098f043b102479bd007aa938e6ea3"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201005+0/PThreadPool.v0.0.20201005.aarch64-linux-musl.tar.gz"
[[PThreadPool]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9b74a3b32a52622ae7c015eaeea710d87093794f"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "2708aa3c3974d93cf24f1258f3e24b9e97449cbd13fc2507d9b55e5b07124d43"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201005+0/PThreadPool.v0.0.20201005.armv6l-linux-gnueabihf.tar.gz"
[[PThreadPool]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "707371db711fef5a439311ce531d62526a51a010"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "14a79524ae726f640b4a121debb68d98bb6c0e085f112bcd83a68bd2a21581b6"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201005+0/PThreadPool.v0.0.20201005.armv6l-linux-musleabihf.tar.gz"
[[PThreadPool]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f48b0ab6fcf55404de758fb17bfea6956efcc150"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "09ca8a22743cd08637ce782ebf7e089ec47e0a2917af1f0e74c3c094926ec952"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201005+0/PThreadPool.v0.0.20201005.armv7l-linux-gnueabihf.tar.gz"
[[PThreadPool]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1864dc3628d502f2576ca0b0da62fb285ba5831a"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "43d51ea68d526bdf055a4070387a35ec7dd95f60b93cf51909450343c969eb40"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201005+0/PThreadPool.v0.0.20201005.armv7l-linux-musleabihf.tar.gz"
[[PThreadPool]]
arch = "i686"
git-tree-sha1 = "885702058acf051c38445c6e6caebd67118978e5"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "111865e49a6822226076023f804743c0f30c096426d10e2ec27d2278f180cb64"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201005+0/PThreadPool.v0.0.20201005.i686-linux-gnu.tar.gz"
[[PThreadPool]]
arch = "i686"
git-tree-sha1 = "9b18a60124ff34b76dd3a1607c1038b0cc73e914"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "35ed89971a04c8714da81e8de9d7a69085e3b29b2b44a0c66ae3232baf668a6e"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201005+0/PThreadPool.v0.0.20201005.i686-linux-musl.tar.gz"
[[PThreadPool]]
arch = "i686"
git-tree-sha1 = "ec6a5f63cba2120b91eca1179e63063dd647685b"
os = "windows"

    [[PThreadPool.download]]
    sha256 = "66056cb8e9f97192578e22e5a39eed6da66c7db8be856ff10b8b9daa4f969318"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201005+0/PThreadPool.v0.0.20201005.i686-w64-mingw32.tar.gz"
[[PThreadPool]]
arch = "powerpc64le"
git-tree-sha1 = "db66747a36bd72589336989f2e3e4fa01fbb14a6"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "c5d46198c9678adc153e4e9e83e879e94c6bddbb2abcd7bc450dd25cfe9052db"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201005+0/PThreadPool.v0.0.20201005.powerpc64le-linux-gnu.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "e9160d1299e76029dd6ff3a7b37d4f2b00c6d743"
os = "macos"

    [[PThreadPool.download]]
    sha256 = "b6524b40eb4f3e93fc0e88623a8ff5db364caedd73c8164ea385a439c7c9b356"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201005+0/PThreadPool.v0.0.20201005.x86_64-apple-darwin.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "8f2fa1ce7e129843018cebe8dec0fa1134714897"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "9439c82b76334f12d6922a6008ceab97d172e9bc809828720aa7982899ed4e14"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201005+0/PThreadPool.v0.0.20201005.x86_64-linux-gnu.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "adb00da69dc00da28ae4e1944fba7eca0e59ef58"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "6bd265b9fe88863ff2b9fadabd8e1dab2a5c55b54b76b8929d1f187a72115a32"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201005+0/PThreadPool.v0.0.20201005.x86_64-linux-musl.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "76233b00a8035489de3b68dbb5986feea014a102"
os = "freebsd"

    [[PThreadPool.download]]
    sha256 = "a01a5997217c37c68d718237fadb90738e9fb3ca61ba6333d41f31cc0b50ee2c"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201005+0/PThreadPool.v0.0.20201005.x86_64-unknown-freebsd.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "58df6398b133c5311d8edc13d65fd6ecf6cf4e0a"
os = "windows"

    [[PThreadPool.download]]
    sha256 = "b1474959f3952fafbe8fe590c5d1372b4613c0efbb040a88c6e4cd604955889c"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201005+0/PThreadPool.v0.0.20201005.x86_64-w64-mingw32.tar.gz"
