[[PThreadPool]]
arch = "aarch64"
git-tree-sha1 = "fae244974d01375eeec7d1756e10acbdf608e4ab"
os = "macos"

    [[PThreadPool.download]]
    sha256 = "25d6efa6b1b9737b1c4e6615067b049502a071c9ecd8b4d371e57a71b6a90c31"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20210414+0/PThreadPool.v0.0.20210414.aarch64-apple-darwin.tar.gz"
[[PThreadPool]]
arch = "aarch64"
git-tree-sha1 = "0a6feb06386068ee4a9027f1d9e6405f394c59d9"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "b1d06a22a38496136430ce2a1ffda3f22997b06b68e49b5464eeccd952fa3ab1"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20210414+0/PThreadPool.v0.0.20210414.aarch64-linux-gnu.tar.gz"
[[PThreadPool]]
arch = "aarch64"
git-tree-sha1 = "08ddb69d8d59282b5d828b5748a41264222e4fd5"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "647fe93543926c089ae576463f7b2c8b0d1689cb56eb09c8b837f9cdae856df0"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20210414+0/PThreadPool.v0.0.20210414.aarch64-linux-musl.tar.gz"
[[PThreadPool]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4fd409bd9f62649afacfdf9d4e24451b01922e4d"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "1247f33cfad4f96575632c66ef6ef6293d92009878326431a226cbc52c666d9c"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20210414+0/PThreadPool.v0.0.20210414.armv6l-linux-gnueabihf.tar.gz"
[[PThreadPool]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fbc6a825a5c54869733ffc339bf68a732fbb1b41"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "b479cdeb88a69e7959af2c55fe93dca2703a28f0a2f49dcc094bebb301fba173"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20210414+0/PThreadPool.v0.0.20210414.armv6l-linux-musleabihf.tar.gz"
[[PThreadPool]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7c61861d92351331411c0b7f1107845e30a130c8"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "5057322e0f3bce27e6d94bf3f20cbed1d8ab744cf78c279bd9cd042db4dfbaae"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20210414+0/PThreadPool.v0.0.20210414.armv7l-linux-gnueabihf.tar.gz"
[[PThreadPool]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fe925c9ca2d23a72c29dab7aa2c6acdb7a6a41b1"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "3523e12a11597f5e1cbc00d22e868b4c0d4af91ba5614cdd1760210d81af23ba"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20210414+0/PThreadPool.v0.0.20210414.armv7l-linux-musleabihf.tar.gz"
[[PThreadPool]]
arch = "i686"
git-tree-sha1 = "a62b560046e88f0744b35776d839a1e99873f81e"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "61a84d023f53c9e6011df279e8a9d79b84f40fa3d6628826ae2f933ff5637232"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20210414+0/PThreadPool.v0.0.20210414.i686-linux-gnu.tar.gz"
[[PThreadPool]]
arch = "i686"
git-tree-sha1 = "efffe1e89e5108af6b2995c30423ba26af066a02"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "c969e91cd3f60554c387176387374084a9fc2ceff06a0bbeefcc03b1bbfe9389"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20210414+0/PThreadPool.v0.0.20210414.i686-linux-musl.tar.gz"
[[PThreadPool]]
arch = "i686"
git-tree-sha1 = "b95910f8d4fe556aea2cd7b7f924582333154e43"
os = "windows"

    [[PThreadPool.download]]
    sha256 = "44b13b2b7b36d756833b5a6fb43b7275ec14f64270774bcf56a18f203ce120d0"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20210414+0/PThreadPool.v0.0.20210414.i686-w64-mingw32.tar.gz"
[[PThreadPool]]
arch = "powerpc64le"
git-tree-sha1 = "313dd445e27bc516d7f53220052a76108dd39d6d"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "2f4086532fc242682e1cd5dfab1c5390ff4075f81052dce7716da195f92b2333"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20210414+0/PThreadPool.v0.0.20210414.powerpc64le-linux-gnu.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "e9bfa5ed579d516798973a88dce18ccba0e1d99a"
os = "macos"

    [[PThreadPool.download]]
    sha256 = "2795a3323e074e204e5cff05bcf042c97396ce60e38928da3d7d958c4fa3d872"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20210414+0/PThreadPool.v0.0.20210414.x86_64-apple-darwin.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "0acf2c6154fd431f1b2456870fe1bed5eda0628a"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "bbfb512879585eb84b83693cdebab398699dd01c1b09cd95644dcdda2fd9d403"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20210414+0/PThreadPool.v0.0.20210414.x86_64-linux-gnu.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "e43614a4db566945ff50020c9e193fccf2789112"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "3c0fdd888f3a48639b5b0e6c40fad3cee24b9ec7e6a64435c4f7b981846e67b9"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20210414+0/PThreadPool.v0.0.20210414.x86_64-linux-musl.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "7a8470d2e7dfd8401512523c3404ba7502b39ee9"
os = "freebsd"

    [[PThreadPool.download]]
    sha256 = "b17c639fda593327dc8aad0a74fe218f9af4ad1fce7c6f508846b83e22c95a12"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20210414+0/PThreadPool.v0.0.20210414.x86_64-unknown-freebsd.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "fe4c767704ddc5aefa28f2c10310fa0e48dfdef8"
os = "windows"

    [[PThreadPool.download]]
    sha256 = "fc19caf6278c0234f5e0bc3e87d734e329b426abf6dc35a25da0b70e73c2e13a"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20210414+0/PThreadPool.v0.0.20210414.x86_64-w64-mingw32.tar.gz"
