[[PThreadPool]]
arch = "aarch64"
git-tree-sha1 = "6250bf81900293b3ab1af3c309cbb5d6b61b6fa1"
os = "macos"

    [[PThreadPool.download]]
    sha256 = "14efb1b22859a9047dced61a97bbc86d1e6faf5b347c21cb416ced1fa542e4e1"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200302+0/PThreadPool.v0.0.20200302.aarch64-apple-darwin.tar.gz"
[[PThreadPool]]
arch = "aarch64"
git-tree-sha1 = "167f0bf0cd1af611dc588e3540bbc0347bc43b59"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "a2f737b609cbf7bd55e946fcbb26c58c81f96c3fb48f9bb0bef0e0f2a5eb6952"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200302+0/PThreadPool.v0.0.20200302.aarch64-linux-gnu.tar.gz"
[[PThreadPool]]
arch = "aarch64"
git-tree-sha1 = "93599c1c19b827c1183920eca1ae5c52517c71b9"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "9ba769a6d2608c8f4cdaacb651bff86a291affc814340acca86a99d06b30ffa6"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200302+0/PThreadPool.v0.0.20200302.aarch64-linux-musl.tar.gz"
[[PThreadPool]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "caaeafd85faf1dc2e6c060e5928b01ac4b4f6713"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "1cd3673462ab1a5bce2c273666ca6bfbee7ee35d947ce0b46728697dfdc4492d"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200302+0/PThreadPool.v0.0.20200302.armv6l-linux-gnueabihf.tar.gz"
[[PThreadPool]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0d4bb4bc553a4115376c97994f4b7de5d1c8a900"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "56d4b2eb79fa29ee874f4302ce33359757a2643a25b448d5d47a5d719e1b88ad"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200302+0/PThreadPool.v0.0.20200302.armv6l-linux-musleabihf.tar.gz"
[[PThreadPool]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6fc738260ec741694c6e52f8d657f91a8521bee7"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "e802b14277fffc647ff1cd33c48912e3708ea376443632737d8fc74576051e0f"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200302+0/PThreadPool.v0.0.20200302.armv7l-linux-gnueabihf.tar.gz"
[[PThreadPool]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7643f7932aec34ad423cd994fb3d8f647f51fdb9"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "1fa0fc7c390e7b28859759ebff521d2e51055ab26f412d9890fb5817014591f7"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200302+0/PThreadPool.v0.0.20200302.armv7l-linux-musleabihf.tar.gz"
[[PThreadPool]]
arch = "i686"
git-tree-sha1 = "451d5d41e9548d83e939d44b5fb7dfcc85d8a619"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "580a863dc271bed0de5eaa21e95ca90f8de66cd014627dcc3b8fd08141bca1d5"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200302+0/PThreadPool.v0.0.20200302.i686-linux-gnu.tar.gz"
[[PThreadPool]]
arch = "i686"
git-tree-sha1 = "f3ee95b38ef3c626652afff0e797df9eb4737ac2"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "e10f0b0b8a36084d749b3cdb8adaca0e1bc1e7f4720a4b441833313c7dc9f926"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200302+0/PThreadPool.v0.0.20200302.i686-linux-musl.tar.gz"
[[PThreadPool]]
arch = "i686"
git-tree-sha1 = "e261b1eddc76801011e9fee7b34b1a074f01895d"
os = "windows"

    [[PThreadPool.download]]
    sha256 = "373fe1a03e4be2b1a422110650105f054852d6eadba0ba95a41debb6664e2f47"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200302+0/PThreadPool.v0.0.20200302.i686-w64-mingw32.tar.gz"
[[PThreadPool]]
arch = "powerpc64le"
git-tree-sha1 = "76bb83c876b9d36b3f3899045f2cec86bccead64"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "2ced287c6268ce8e33d083193f251bfb1937c7e058344389be5449bbb6bd94f9"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200302+0/PThreadPool.v0.0.20200302.powerpc64le-linux-gnu.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "419dc35b7cce5ce5a17f655e5117935ecafdc309"
os = "macos"

    [[PThreadPool.download]]
    sha256 = "3b97348eb5fb896f966c4abe369bae6eae26c7b5839fec125c55ce7e10f1048b"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200302+0/PThreadPool.v0.0.20200302.x86_64-apple-darwin.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "406c8a15d03e8f73ff01e483c4d71c4d8ebc5fa0"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "e3ab356cd63825e66b153d94d1360b4d94433719b08906636fdae09178ea2b9f"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200302+0/PThreadPool.v0.0.20200302.x86_64-linux-gnu.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "0cf0f3119d3ee043f0435ef45adac46e15dd4944"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "28a352a047d2814f7c29b7c43d4f6412f878a5f28a43093a4a26ba5aaa914574"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200302+0/PThreadPool.v0.0.20200302.x86_64-linux-musl.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "4a10331019e304cc2d257348214611b1c79e8003"
os = "freebsd"

    [[PThreadPool.download]]
    sha256 = "73aff2364a71bb3d0fce513006f77f69e3e432ea786e5ce2e21a0c33d043cb47"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200302+0/PThreadPool.v0.0.20200302.x86_64-unknown-freebsd.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "7c77c44a48c60a6de78d19f2fb808732bef44fc2"
os = "windows"

    [[PThreadPool.download]]
    sha256 = "0ef139f9bca8388d748dcc0879eb24cd78f0dcaa47365a114477a2f830d57db1"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200302+0/PThreadPool.v0.0.20200302.x86_64-w64-mingw32.tar.gz"
