[[PThreadPool]]
arch = "aarch64"
git-tree-sha1 = "fd9f77a99dfe9ad63fd7a8553f3d42ca100cdb61"
os = "macos"

    [[PThreadPool.download]]
    sha256 = "b2fec478a69886ad06fb21ad9f38296e69caa0b3c41c775d06bc9beb26079f69"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201206+0/PThreadPool.v0.0.20201206.aarch64-apple-darwin.tar.gz"
[[PThreadPool]]
arch = "aarch64"
git-tree-sha1 = "24a036a7069ac799181bd5497ba7dac931d3e21e"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "52e75147e67fdcb25db5dbc2baf1ccf392abb748b9eba30bb412de6b43a83de1"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201206+0/PThreadPool.v0.0.20201206.aarch64-linux-gnu.tar.gz"
[[PThreadPool]]
arch = "aarch64"
git-tree-sha1 = "16b58226d7dceebdf9bc6954ab550fd0b9905dfb"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "fc31c744dcb83bf2068f095fad72d29a2d07a6d9555972f4460aa1eb03600090"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201206+0/PThreadPool.v0.0.20201206.aarch64-linux-musl.tar.gz"
[[PThreadPool]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f3cf2208fed339945b13c8b407f230422722e694"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "476af406ef3f60cbaa74bae4a80c7520a862bb05d26fb294dfb1231a3a7b75ef"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201206+0/PThreadPool.v0.0.20201206.armv6l-linux-gnueabihf.tar.gz"
[[PThreadPool]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "66839dcdf818363ce2acbc2ac63f09c413499e93"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "4004d291abbf2cd3ef56854fa65ae9257ffdf90d134af827a70629aabfd0a809"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201206+0/PThreadPool.v0.0.20201206.armv6l-linux-musleabihf.tar.gz"
[[PThreadPool]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6ca84644572ff671212530a23217bed6eb17937f"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "035a1ef1c1458aff4f0bcbd0c28e20b9ae057575540498508dfade7913deca4b"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201206+0/PThreadPool.v0.0.20201206.armv7l-linux-gnueabihf.tar.gz"
[[PThreadPool]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "55bc6ea05f42baf67684d55729c244253b44f497"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "82cc755e6403601d904cf22e942a153b2ba55e77d6d49085136f8ebff36b7268"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201206+0/PThreadPool.v0.0.20201206.armv7l-linux-musleabihf.tar.gz"
[[PThreadPool]]
arch = "i686"
git-tree-sha1 = "28dcb91714d0c4cb45751f80c99f6743beb9eaed"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "7d82e61f3420c0f7cab0e0f930014b54259acff50036c06e685e77e1593bb781"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201206+0/PThreadPool.v0.0.20201206.i686-linux-gnu.tar.gz"
[[PThreadPool]]
arch = "i686"
git-tree-sha1 = "c65c92088d1c74ba28f523ee7deab20af386261d"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "ec795256c3c8e30597a1e04064afd617646264c660b91bdfd9d4110b0c2299f2"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201206+0/PThreadPool.v0.0.20201206.i686-linux-musl.tar.gz"
[[PThreadPool]]
arch = "i686"
git-tree-sha1 = "8965a86760c4aa5f079b8d7e849849474b6c3d4d"
os = "windows"

    [[PThreadPool.download]]
    sha256 = "c01250fd1824df3d7ca911b17b060b81a55a1adbb6c0f402e4dfcb9d368524b1"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201206+0/PThreadPool.v0.0.20201206.i686-w64-mingw32.tar.gz"
[[PThreadPool]]
arch = "powerpc64le"
git-tree-sha1 = "5644a8a2fab99e7123a3d62bd9ec62e1baf24038"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "90797ffa1e1c170f7db6991051e8cb5a6cde8398110b5a1c2019335ac6cba3c8"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201206+0/PThreadPool.v0.0.20201206.powerpc64le-linux-gnu.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "c882c8521adc6e8f0c2fc431019b664bddcfdc04"
os = "macos"

    [[PThreadPool.download]]
    sha256 = "2fbde7cab952c26265eee75ae37748ce6309b7563b1254d86762d3fe0bf63cff"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201206+0/PThreadPool.v0.0.20201206.x86_64-apple-darwin.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "5d05b4cbae464b73146aaf03b80418d5a64c9c74"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "8fb460d0b60ada3b8d505e201594adc41edb7410b27c0576b4cf8e8dea65e82b"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201206+0/PThreadPool.v0.0.20201206.x86_64-linux-gnu.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "a87554062525a5144fe10e22ba794bd09b031882"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "8c969aa46a905e99a1257ccff7b165a68c66f95699d55672e4a54ca021721665"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201206+0/PThreadPool.v0.0.20201206.x86_64-linux-musl.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "615d35b52ccaf86257ed0b931e3b24e94e5c3dcd"
os = "freebsd"

    [[PThreadPool.download]]
    sha256 = "56c6beae030665e0100a3f9a3d164750bb2ad9fdcc5dda83451c0ce1fbb9f1c9"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201206+0/PThreadPool.v0.0.20201206.x86_64-unknown-freebsd.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "b8618e0905b73177fa11618e1043ab8f6a6d153c"
os = "windows"

    [[PThreadPool.download]]
    sha256 = "1305e8a7c210513fe7af5070b9ed593cec38257dc4f8974a274eef6e3c0f6df9"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20201206+0/PThreadPool.v0.0.20201206.x86_64-w64-mingw32.tar.gz"
