[[PThreadPool]]
arch = "aarch64"
git-tree-sha1 = "9182fc4a1a6b88431b12419045308c210cb287c4"
os = "macos"

    [[PThreadPool.download]]
    sha256 = "96d32864fed26ca3820306883261031e24727d20e35d43a46af420c2fd5427f9"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200616+0/PThreadPool.v0.0.20200616.aarch64-apple-darwin.tar.gz"
[[PThreadPool]]
arch = "aarch64"
git-tree-sha1 = "9b3070682fffb9a525a388e3c6cc33307c9b43b7"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "a8a8358220482d8e118e8018d1e9ec10facc10ff5aa485d01ee352b7e55f5782"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200616+0/PThreadPool.v0.0.20200616.aarch64-linux-gnu.tar.gz"
[[PThreadPool]]
arch = "aarch64"
git-tree-sha1 = "b16cb202acaaa0ae6abae6c06b410a7ad402b186"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "e69cf0d83788757e3f8be88d8960017c1feba75e5f03bf6bef589e19f28b138a"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200616+0/PThreadPool.v0.0.20200616.aarch64-linux-musl.tar.gz"
[[PThreadPool]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3092def4835b88f9fdbede762e07ef43a579ac82"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "9010f27f7d7e65d05126bb3d32017c5a62fa3c5c2d99068172a8e7f4c3eb6ac0"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200616+0/PThreadPool.v0.0.20200616.armv6l-linux-gnueabihf.tar.gz"
[[PThreadPool]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "37ef2ebfab80169e3bd66fc4df2a7da70186fe26"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "71f142edbd7db169b8183411ae4a757749c98dbcfea2a7dcc1fda93aaf82e675"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200616+0/PThreadPool.v0.0.20200616.armv6l-linux-musleabihf.tar.gz"
[[PThreadPool]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1dcca3530e4882c3b22f180f6eb22ff5ea0267bf"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "81d7907e21fd000a9736b8cb85fc2710c99561a1019d8a30a47136c5c0f7f068"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200616+0/PThreadPool.v0.0.20200616.armv7l-linux-gnueabihf.tar.gz"
[[PThreadPool]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fcb71b95e4496145bc9431f6612882494ef9be17"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "8756b483ad5d8a9ef7e3eb5fad70641a4743d6d1f8c775694f9e3c1625ed62d8"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200616+0/PThreadPool.v0.0.20200616.armv7l-linux-musleabihf.tar.gz"
[[PThreadPool]]
arch = "i686"
git-tree-sha1 = "8cb05917cf706f6f78fd44464432e76867986fcf"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "3d946e76710baf565456fab09aee5ee5fed747754edf0692238c66e5b16ec721"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200616+0/PThreadPool.v0.0.20200616.i686-linux-gnu.tar.gz"
[[PThreadPool]]
arch = "i686"
git-tree-sha1 = "7fb4e4a4380c50ca21c96f591d8a4084d9e0589d"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "11d44a35d3fde85a1a0e5f25ef202ea69b1a835f7160da37585e76c6b117741f"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200616+0/PThreadPool.v0.0.20200616.i686-linux-musl.tar.gz"
[[PThreadPool]]
arch = "i686"
git-tree-sha1 = "df0eaafdbcb6b712904bbc05dafa70d45c21f910"
os = "windows"

    [[PThreadPool.download]]
    sha256 = "dfaf1800a19536322243b0ea3d7229c4d7e00ed8d07774b9ee08ae4b4ad7ee6a"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200616+0/PThreadPool.v0.0.20200616.i686-w64-mingw32.tar.gz"
[[PThreadPool]]
arch = "powerpc64le"
git-tree-sha1 = "58a3977d5620af317b307627895016ab2b8bddbd"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "1a346759ae3f68a2f88cf426e829beca50a2f77bb35e2d948f3f454303e4c26b"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200616+0/PThreadPool.v0.0.20200616.powerpc64le-linux-gnu.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "e55a959540ba5772a5b6820c87e9a5b9402414a2"
os = "macos"

    [[PThreadPool.download]]
    sha256 = "52779f20d0602601c34f4f623833147ee633a5b5f31e1f58b46347bb02dc470d"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200616+0/PThreadPool.v0.0.20200616.x86_64-apple-darwin.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "6ac7123ecb6c37424940daca4bae6e9003b80ece"
libc = "glibc"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "5e0cce8b4f2dc43529da68e79bdb07035a4a9ea149145ad8a6ab113d0c90b04b"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200616+0/PThreadPool.v0.0.20200616.x86_64-linux-gnu.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "697df4620728484e643d1c3f069ba8e899a46bc3"
libc = "musl"
os = "linux"

    [[PThreadPool.download]]
    sha256 = "791d2809013bdb60d3da62877609a467e126a2f1a6bb1c967c2abbe063a0a069"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200616+0/PThreadPool.v0.0.20200616.x86_64-linux-musl.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "97704a51e2471229fa85749f07b4921d818faad2"
os = "freebsd"

    [[PThreadPool.download]]
    sha256 = "147f3583d44ba18ff09ca38039fe8cff74342c74dab0d9cab8dc8b962d765ba5"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200616+0/PThreadPool.v0.0.20200616.x86_64-unknown-freebsd.tar.gz"
[[PThreadPool]]
arch = "x86_64"
git-tree-sha1 = "d141726f80dc515f882167ee15bd34c8f8ebe9b1"
os = "windows"

    [[PThreadPool.download]]
    sha256 = "1da085571b9e99702d1da575f68c8484e4e3a98882c290de814443a175ffc345"
    url = "https://github.com/JuliaBinaryWrappers/PThreadPool_jll.jl/releases/download/PThreadPool-v0.0.20200616+0/PThreadPool.v0.0.20200616.x86_64-w64-mingw32.tar.gz"
