# Autogenerated wrapper script for PThreadPool_jll for i686-w64-mingw32
export libpthreadpool

JLLWrappers.@generate_wrapper_header("PThreadPool")
JLLWrappers.@declare_library_product(libpthreadpool, "libpthreadpool.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libpthreadpool,
        "bin\\libpthreadpool.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
