# Autogenerated wrapper script for PThreadPool_jll for x86_64-apple-darwin
export libpthreadpool

JLLWrappers.@generate_wrapper_header("PThreadPool")
JLLWrappers.@declare_library_product(libpthreadpool, "@rpath/libpthreadpool.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libpthreadpool,
        "lib/libpthreadpool.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
