# Autogenerated wrapper script for PThreadPool_jll for x86_64-w64-mingw32
export libpthreadpool

using CPUInfo_jll
JLLWrappers.@generate_wrapper_header("PThreadPool")
JLLWrappers.@declare_library_product(libpthreadpool, "libpthreadpool.dll")
function __init__()
    JLLWrappers.@generate_init_header(CPUInfo_jll)
    JLLWrappers.@init_library_product(
        libpthreadpool,
        "bin\\libpthreadpool.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
